[package]
name = "ScottOS"
version = "0.0.1"
edition = "2024"
authors = ["Scott Fitzhugh <scott@fitzhugh.me>"]

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]